[build]
  base = "guard-duty-system"
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next_server"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"
